version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 3
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 3
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.0
