kind: pipeline
type: kubernetes
name: default

clone:
  depth: 1

steps:
  - name: build
    image: circleci/ruby:2.6.5-node-browsers
    volumes:
    - name: bundle
      path: /usr/local/bundle
    commands:
      - bin/setup
      - bin/build

volumes:
  - name: bundle
    temp: {}
