rootUrl: http://localhost:4000/
screenshotsDir: reports/screenshots
browsers:
  PhantomJS:
    desiredCapabilities:
      browserName: phantomjs
system:
  coverage:
    exclude:
      - bower_components/
      - css/
      - tasks/
      - images/
      - js/
