why_us:
  title: Why us?
  description: We are Developers who helped to grow successful products. We offer a fully managed dedicated tech team consisting of full-stack Ruby on Rails, Vue.js, React software engineers.
  items:
  - We take all the candidates through the highly effective 4-Step interview process where they are tested in all the aspects of their job.
  - Our engineers worked together as a team on different projects so the onboarding is shortened significantly
  - By Integrating transparency, flexibility, and work culture into our internal processes during the past 15 years, we’ve developed our own unique framework for the remote distributed teams.
jetthoughts_do:
  title: JetThoughts do
  items:
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
contact_form:
  title: Haven't Found the Right Job?
  sub_title: Fill out your contact information so we can call you
