jetthoughts_do:
  title: JetThoughts do
  items:
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
    - Sourse & hire with candidate (from our pool)
discuss_your_project:
  title: What's next?
  items:
    - After that, well develop a proposal for you.
    - After that, well develop a proposal for you.
    - After that, well develop a proposal for you.